#!/bin/sh
set -eu

exec python /workspace/rl/train.py \
  --iterations "${RL_ITERATIONS:-1000}" \
  --games "${RL_GAMES:-8}" \
  --simulations "${RL_SIMULATIONS:-100}" \
  --wall-candidates "${RL_WALL_CANDIDATES:-20}" \
  --temperature-moves "${RL_TEMPERATURE_MOVES:-16}" \
  --heuristic-start "${RL_HEURISTIC_START:-0.65}" \
  --heuristic-end "${RL_HEURISTIC_END:-0.10}" \
  --heuristic-decay "${RL_HEURISTIC_DECAY:-100}" \
  --train-steps "${RL_TRAIN_STEPS:-100}" \
  --batch-size "${RL_BATCH_SIZE:-64}" \
  --replay-capacity "${RL_REPLAY_CAPACITY:-100000}" \
  --channels "${RL_CHANNELS:-32}" \
  --blocks "${RL_BLOCKS:-3}" \
  --learning-rate "${RL_LEARNING_RATE:-0.001}" \
  --learning-rate-mid "${RL_LEARNING_RATE_MID:-0.0003}" \
  --learning-rate-final "${RL_LEARNING_RATE_FINAL:-0.0001}" \
  --lr-mid-iteration "${RL_LR_MID_ITERATION:-100}" \
  --lr-final-iteration "${RL_LR_FINAL_ITERATION:-250}" \
  --replay-recent-fraction "${RL_REPLAY_RECENT_FRACTION:-0.60}" \
  --replay-recent-window "${RL_REPLAY_RECENT_WINDOW:-30000}" \
  --threads "${RL_THREADS:-2}" \
  --workers "${RL_WORKERS:-2}" \
  --eval-every "${RL_EVAL_EVERY:-5}" \
  --eval-games "${RL_EVAL_GAMES:-20}" \
  --eval-random-games "${RL_EVAL_RANDOM_GAMES:-20}" \
  --eval-fixed-seed "${RL_EVAL_FIXED_SEED:-20260818}" \
  --eval-simulations "${RL_EVAL_SIMULATIONS:-100}" \
  --eval-opening-plies "${RL_EVAL_OPENING_PLIES:-2}" \
  --promotion-games "${RL_PROMOTION_GAMES:-20}" \
  --promotion-random-games "${RL_PROMOTION_RANDOM_GAMES:-20}" \
  --promotion-score "${RL_PROMOTION_SCORE:-0.55}" \
  --promotion-seat-win-rate "${RL_PROMOTION_SEAT_WIN_RATE:-0.40}" \
  --snapshot-every "${RL_SNAPSHOT_EVERY:-10}" \
  --max-snapshots "${RL_MAX_SNAPSHOTS:-12}" \
  --league-current-weight "${RL_LEAGUE_CURRENT_WEIGHT:-0.50}" \
  --league-champion-weight "${RL_LEAGUE_CHAMPION_WEIGHT:-0.30}" \
  --league-history-weight "${RL_LEAGUE_HISTORY_WEIGHT:-0.20}" \
  --history-recent-snapshots "${RL_HISTORY_RECENT_SNAPSHOTS:-6}" \
  --history-champions "${RL_HISTORY_CHAMPIONS:-3}" \
  --save-replay-every "${RL_SAVE_REPLAY_EVERY:-5}" \
  --output /workspace/checkpoints/quoridor_latest.pt \
  --best-output /workspace/checkpoints/quoridor_best.pt \
  --league-dir /workspace/checkpoints/league \
  --replay /workspace/replay/quoridor_replay.npz \
  --metrics /workspace/metrics/training.jsonl \
  --resume
